### ISSUE TITLE
HttpServer不能恰当处理数据量大的请求体

### ISSUE THREAD

**Issue by hanyh2004** [shenzhe/zphp#13]
Socket\Callback\HttpServer
1，YAC保存临时数据有64M限制 ,
2，数据全部临时保存在内存不恰当

 public function onReceive()
    {
        $params = func_get_args();
        $_data = $params[3];
        $serv = $params[0];
        $fd = $params[1];
        $parser = new HttpParser();
        $buffer = $this->cache->getBuff($fd);
        $nparsed = (int) $this->cache->getBuff($fd, 'nparsed');
        $buffer .= $_data;
        $nparsed = $parser->execute($buffer, $nparsed);
        if($parser->hasError()) {
            $serv->close($fd, $params[2]);
            $this->_clearBuff($fd);
        } elseif ($parser->isFinished()) {
            $this->_clearBuff($fd);
            $this->onSend($fd, $this->_getData($parser->getEnvironment()));
        } else {
            $buffer = $this->cache->setBuff($fd, $buffer);
            $nparsed = (int) $this->cache->setBuff($fd, $nparsed, 'nparsed');
        }
    }

**Comment by shenzhe** [comment]
谢谢，现已经使用swoole内置的http_server了。
