### ISSUE TITLE
zphp Zpack 协议改进

### ISSUE THREAD

**Issue by luxixing** [shenzhe/zphp#15]
我看到在protocl里面的Zpack.php这个，有个对客户端发上来的数据进行组包的过程，然后swoole 1.7.3不是有了open_length_check 这个特性了吗，可以依赖这个特性来进行数据的收发，不用使用PHP自己去实现组包

**Comment by shenzhe** [comment]
是的，这是个遗留问题，可以当做一个第三方协议的示例吧。
