### ISSUE TITLE
ZPHP在多线程下模式下运行抛出异常

### ISSUE THREAD

**Issue by ndj888** [shenzhe/zphp#28]
arning: swoole_server::__construct(): PHP can not running at multi-threading. Reset mode to SWOOLE_MODE_BASE in /usr/sr
/myapp/vendor/keaixiaou/zphp/ZPHP/Socket/Adapter/Swoole.php on line 43

**Comment by shenzhe** [comment]
php的多线程有问题，swoole已不支持，你可以用多进程或base模式。
