### ISSUE TITLE
建议ZPHP\Socket\Callback\Swoole 回调方法中添加 Request:setFd($fd)

### ISSUE THREAD

**Issue by xufei100** [shenzhe/zphp#30]
因为Request类是静态全局类，如果再swoole 实现类里面 没有显示的设置 Request:setFd  ,会导致在实现类里面调用 Request:getFd()  可能取到 上次请求设置的值  ，建议在 接口类中的 回调方法 onConnect,onClose ，如同 onReceive 显示调用 Request:setFd($fd) 

另外根据我的测试，我发现 Request的生命周期是 同work 一致的，此处是否使用 request 对象 更好，不然有可能获取一些莫名的值

**Comment by shenzhe** [comment]
public function doReceive($server, $fd, $from_id, $data)
    {
        Protocol\Request::setFd($fd);
        $this->onReceive($server, $fd, $from_id, $data);
    }

这里会自动设置

这里的Request和swoole的request作用是不一样的。有可能获取莫名的值这个需要测试，正常不会。每次请求过来之后，都会init一下Request
https://github.com/shenzhe/zphp/blob/master/ZPHP/Protocol/Request.php#L44-L66

**Comment by xufei100** [comment]
是的，我上次遇到的问题是这样产生的，SLB端口检查,只建立TCP握手， 只触发 onConnect，OnClose, 不会触发 OnReceive ,我在OnClose里面 设置根据 fd 清理工作，因为Request 是全局的，这样就导致  我获取上次 设置过的连接的 fd ，清理了不该清理的连接 ，所以 我建议 在 OnConnect 和 OnClose 也封装调用  Protocol\Request:setFd

这是静态类常驻引起问题，这基本需要对所有公开调用的方法都需要进行初始化，不然就会出现获取一些未知的值，当然如果操作注意这些，一般不会犯什么错误
一个最典型的例子 就是 每次虽然  self::setRequestId(); 
但除了第一次请求生成 requestId 后，后面都不会生成，因为它会从 上次设置了self::$_headers ，下次请求就直接获取了

**Comment by shenzhe** [comment]
嗯，最新已经修复此问题。

static的成员在swoole这类场景下使用要非常小心
