### ISSUE TITLE
低版本Linux内核和Mac OSX不支持进程重命名

### ISSUE THREAD

**Issue by cenchy** [shenzhe/zphp#31]
低版本Linux内核和Mac OSX不支持进程重命名
PHP Warning:  cli_set_process_title(): cli_set_process_title had an error: Not initialized correctly in /data/server/swoole/zphpdemo/demo_composer/vendor/zphp/zphp/ZPHP/Socket/Callback/Swoole.php on line 83

**Comment by shenzhe** [comment]
嗯，确实不支持，一个Warning,影响不大
