### ISSUE TITLE
希望zphp增加服务start、stop、restart、reload方法

### ISSUE THREAD

**Issue by caojiabin2012** [shenzhe/zphp#37]
现在启动服务是：php main.php socket_http 
在原来的基础上加个参数，比如加了reload，根据$argv[3]来区分操作，这样就实现了。
希望桶哥个加上，这样我就不用每次都修改ZPHP.php的run方法了，希望采纳。

**Comment by shenzhe** [comment]
这个是外部的功能，自己包装成一个标准的shell脚本来控制会更好
